### ISSUE TITLE
How to programmatically select date?

### ISSUE THREAD

**Issue by albert0m** [mduccc/flutter_calendar_week#1]
great library, my only issue is that the selected date on the calendar stays always the same even if I refresh the widget. Is there any way to reset the indicator or to programmatically select a date?

**Comment by mduccc** [comment]
Programmatically select a date, this feature will appear in the next version. Thank you.

**Comment by albert0m** [comment]
thank you for the update, that works but only after I opened the calendar. 
I will try to explain all the steps to reproduce this problem:

- Open the page with the calendar, today is July 3d.
- I click on July 4th, the _selectedDate is updated and I can draw my content for July 4th.
- Close the page with the calendar, reopen it.
- The _selectedDate is July 3rd (today), but the highlighted date is still July 4th, but without drawing my content for July 4th. The loaded content is for the default _selectedDate, July 3rd.

It looks like it caches the previous click without clearing it when I reload it.

**Comment by mduccc** [comment]
Fix it in the next commit.

**Comment by albert0m** [comment]
hi, any updates for the next commit? we're about to deliver our app and this is the only thing that looks a little off! thank you for your work!

**Comment by mduccc** [comment]
> hi, any updates for the next commit? we're about to deliver our app and this is the only thing that looks a little off! thank you for your work!

Please update to the `flutter_calendar_week: 0.2.1+1` version
