### ISSUE TITLE
Localizations

### ISSUE THREAD

**Issue by Gyurmatag** [mduccc/flutter_calendar_week#13]
Is there any way I can make month names and day names localizations and to make the week start with Monday? I really want it to be in the language of the current locale settings on the phone.

I think this might be a great feature.

Thank you for your help!

**Comment by mduccc** [comment]
You can use:
` dayOfWeek: ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN']`
and define different name by your localizations
