### ISSUE TITLE
Set what day the week starts with

### ISSUE THREAD

**Issue by Legolaszstudio** [mduccc/flutter_calendar_week#14]
# Set what day the week starts with

I think the title explains my feature request, but here's some more detail:
Add a parameter to CalendarWeek to set what day the week showing starts with like this:
```
CalendarWeek(
          controller: _controller,
          height: 100,
          minDate: DateTime.now().add(
            Duration(days: -365),
          ),
          maxDate: DateTime.now().add(
            Duration(days: 365),
          ),
         firstWeekDay: DateTime.monday,
)
```
So the above code would show the weeks starting mondays.

**Comment by mduccc** [comment]
You can achieve it by chose `minDate` as Monday

**Comment by Legolaszstudio** [comment]
Thanks, I didn't notice

**Comment by Shtibel** [comment]
Hi @mduccc 
How exactly can I set that every week will start on Sunday ?
I tried like this:
`minDate : "Sunday"`
But the week is not starting from Sunday

Thank you

**Comment by mandeepWorksdelight** [comment]
You can archive this with 
//Get date of this week's Sunday
var dayOfWeek = 1;
DateTime date = DateTime.now();
var lastSunday = date.subtract(Duration(days: date.weekday - dayOfWeek))

minDate: lastSunday.add(
  Duration(days: -365),
)
