### ISSUE TITLE
flutter web not scrolling

### ISSUE THREAD

**Issue by Innova73** [mduccc/flutter_calendar_week#34]
Hi, great widget. it has only one problem it doesn't scroll the days, android is perfect

**Comment by mduccc** [comment]
Thank you for opening the issue.

I have created a pull request that supports more scroll behavior.

**Comment by mduccc** [comment]
> Hi, great widget. it has only one problem it doesn't scroll the days, android is perfect

@Innova73  Thank you for opening the issue.

I have created a pull request that supports more scroll behavior.
