### ISSUE TITLE
new version of flutter does not support flat button

### ISSUE THREAD

**Issue by AndrewDavydenko** [mduccc/flutter_calendar_week#36]
<img width="913" alt="Screenshot 2022-09-06 at 12 35 19" src="https://user-images.githubusercontent.com/20084357/188601118-e1bec9b5-e604-40c4-8111-66980cafdc7d.png">

**Comment by mduccc** [comment]
> <img alt="Screenshot 2022-09-06 at 12 35 19" width="913" src="https://user-images.githubusercontent.com/20084357/188601118-e1bec9b5-e604-40c4-8111-66980cafdc7d.png">

Thank you!

I will be working on that soon!

**Comment by AndrewDavydenko** [comment]
Hi again! Could you please clarify when I should update the package, my
pipeline on GitHub doesn’t pass now.

вт, 6 вер. 2022 р. о 13:04 Minh Duc ***@***.***> пише:

**Comment by AhmedAElllatif** [comment]
@mduccc any update

**Comment by mduccc** [comment]
Hi @AndrewDavydenko, @AhmedAElllatif 

I made version 3.0.0, resolved that issue!
